name: Nix Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v14

      - name: Install nixpkgs-fmt
        run: nix-env -iA nixpkgs.nixpkgs-fmt

      - name: Check Nix formatting
        run: find . -name '*.nix' -exec nixpkgs-fmt --check {} \;

      - name: Install nix-lint
        run: nix-env -iA nixpkgs.nix-lint

      - name: Lint Nix expressions
        run: find . -name '*.nix' -exec nix-lint {} \;

      - name: Build
        run: nix-build
